# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/f/程序设计/大一上/大作业/Bookstore-2025-main/Bookstore-2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/f/程序设计/大一上/大作业/Bookstore-2025-main/Bookstore-2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/程序设计/大一上/大作业/Bookstore-2025-main/Bookstore-2025/CMakeFiles /mnt/f/程序设计/大一上/大作业/Bookstore-2025-main/Bookstore-2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/程序设计/大一上/大作业/Bookstore-2025-main/Bookstore-2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bookstore_app

# Build rule for target.
bookstore_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bookstore_app
.PHONY : bookstore_app

# fast build rule for target.
bookstore_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/build
.PHONY : bookstore_app/fast

src/Token.o: src/Token.cpp.o
.PHONY : src/Token.o

# target to build an object file
src/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/Token.cpp.o
.PHONY : src/Token.cpp.o

src/Token.i: src/Token.cpp.i
.PHONY : src/Token.i

# target to preprocess a source file
src/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/Token.cpp.i
.PHONY : src/Token.cpp.i

src/Token.s: src/Token.cpp.s
.PHONY : src/Token.s

# target to generate assembly for a file
src/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/Token.cpp.s
.PHONY : src/Token.cpp.s

src/book.o: src/book.cpp.o
.PHONY : src/book.o

# target to build an object file
src/book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/book.cpp.o
.PHONY : src/book.cpp.o

src/book.i: src/book.cpp.i
.PHONY : src/book.i

# target to preprocess a source file
src/book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/book.cpp.i
.PHONY : src/book.cpp.i

src/book.s: src/book.cpp.s
.PHONY : src/book.s

# target to generate assembly for a file
src/book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/book.cpp.s
.PHONY : src/book.cpp.s

src/log.o: src/log.cpp.o
.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/storage.o: src/storage.cpp.o
.PHONY : src/storage.o

# target to build an object file
src/storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/storage.cpp.o
.PHONY : src/storage.cpp.o

src/storage.i: src/storage.cpp.i
.PHONY : src/storage.i

# target to preprocess a source file
src/storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/storage.cpp.i
.PHONY : src/storage.cpp.i

src/storage.s: src/storage.cpp.s
.PHONY : src/storage.s

# target to generate assembly for a file
src/storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/storage.cpp.s
.PHONY : src/storage.cpp.s

src/user.o: src/user.cpp.o
.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i
.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s
.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bookstore_app.dir/build.make CMakeFiles/bookstore_app.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bookstore_app"
	@echo "... src/Token.o"
	@echo "... src/Token.i"
	@echo "... src/Token.s"
	@echo "... src/book.o"
	@echo "... src/book.i"
	@echo "... src/book.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/storage.o"
	@echo "... src/storage.i"
	@echo "... src/storage.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

